version: "3.9"
services: 
  web:
    image: fervo8564/webandtech
    ports:
      - "8443:8443"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ec2-44-194-92-192.compute-1.amazonaws.com:5432/df61ip4spl1gtn
      - SPRING_DATASOURCE_USERNAME=nokxfzhoweailt
      - SPRING_DATASOURCE_PASSWORD=4dcdbcd230adc7a742697c006b64ce540734d2b8f71c43bc82bbff5193152b21
    volumes:
      - .:/usr/app
